name: app_coinlore_flutter
description: A Flutter app to display cryptocurrency data using CoinLore API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  graphic: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
